sudo: required
services:
  - docker

before_install:
  - docker build -t brunokarpo/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true brunokarpo/react-test npm run test

after_sucess:
  - docker build -t brunokarpo/multi-client ./client
  - docker build -t brunokarpo/multi-nginx ./nginx
  - docker build -t brunokarpo/multi-server ./server
  - docker build -t brunokarpo/multi-worker ./worker
  # Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push brunokarpo/multi-client
  - docker push brunokarpo/multi-nginx
  - docker push brunokarpo/multi-server
  - docker push brunokarpo/multi-worker